name: Deploy MarriageStory Rest API on Azure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git
      uses: actions/checkout@v3
    
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_APP_PORT: 5000
        envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
        envkey_JWT_ACCESS_TOKEN_SECRET: ${{ secrets.JWT_ACCESS_TOKEN_SECRET }}
        envkey_JWT_ACCESS_TOKEN_EXPIRED: Pawang <${{ secrets.JWT_ACCESS_TOKEN_EXPIRED }}>
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/marriage-story:latest
        
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          docker rm -f marriage-story
          docker image rm -f ${{ secrets.DOCKERHUB_USERNAME }}/marriage-story:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/marriage-story:latest
          docker run -d -p 5000:5000 --restart always -v /home/marriagestory/marriage-story/public:/usr/src/app/public --name marriage-story ${{ secrets.DOCKERHUB_USERNAME }}/marriage-story:latest
